In [1]:
import numpy as np
from numpy.linalg import norm
from numpy.linalg import qr
from numpy.linalg import eig



def qrDecomposition(matrix):
    matrix = np.array(matrix)
    qM = np.zeros(matrix.shape)
    
    for i in range(matrix.shape[1]):
        # a é a coluna de A
        a = matrix[:,i]
        w = np.copy(a)
        for s in range(qM.shape[1]):            
            w -= (qM[:,s].dot(a))*qM[:,s]       
        q = w/norm(w)
        qM[:,i] = q
        
#     print("\n Q :\n",qM)
#     print("\n Identity: \n", qM.T.dot(qM))

#     verificando se os vetores são ortogonais entre si
#     print("\n zero ?: ", qM[:,0].dot(qM[:,1]))
#     print("\n zero ?: ", qM[:,1].dot(qM[:,2]))
#     print("\n zero ?: ", qM[:,0].dot(qM[:,2]))
    
    rM = qM.T.dot(matrix)
            
    
#     print("\n q.T.dot*A: \n", qM.T.dot(matrix))

    
#     print("\n QR: \n", qM.dot(rM) )
    
    return qM, rM


def qrAlgorithm(q,r):
    A = r.dot(q)
    
    for i in range(100):
        
        q,r = qrDecomposition(A)
        A = r.dot(q)
#         print("\n", np.diag(r))
    return np.diag(r)   
    

In [2]:
#np.random.seed(0)
#np.random.seed(1234)
A = np.random.rand(3,3)
#A = np.array([[1,1,0],[0,1,2],[1,0,-1],[0,1,3]],dtype='float64')
print("\n A:\n",A)

qMatrix,rMatrix = qrDecomposition(A)



q,r = qr(A)
print("\nnumpy Q: \n",q)
print("numpy R: \n",r)
print("numpy QR: \n",q.dot(r))

print("\nNossa Q: \n", qMatrix)
print("Nossa R: \n", rMatrix)
print("Nossa QR: \n", qMatrix.dot(rMatrix))


 A:
 [[ 0.13367596  0.98513102  0.84594807]
 [ 0.86706716  0.37392732  0.6368964 ]
 [ 0.34046109  0.28064583  0.71247776]]

numpy Q: 
 [[-0.14204872  0.98073712 -0.13407785]
 [-0.92137571 -0.18050885 -0.34421411]
 [-0.36178579  0.0746409   0.92926841]]
numpy R: 
 [[-0.94105711 -0.58599782 -0.96475104]
 [ 0.          0.91960503  0.76786721]
 [ 0.          0.          0.32943145]]
numpy QR: 
 [[ 0.13367596  0.98513102  0.84594807]
 [ 0.86706716  0.37392732  0.6368964 ]
 [ 0.34046109  0.28064583  0.71247776]]

Nossa Q: 
 [[ 0.14204872  0.98073712 -0.13407785]
 [ 0.92137571 -0.18050885 -0.34421411]
 [ 0.36178579  0.0746409   0.92926841]]
Nossa R: 
 [[  9.41057105e-01   5.85997823e-01   9.64751044e-01]
 [ -3.81639165e-17   9.19605028e-01   7.67867215e-01]
 [ -4.99600361e-16  -5.55111512e-17   3.29431452e-01]]
Nossa QR: 
 [[ 0.13367596  0.98513102  0.84594807]
 [ 0.86706716  0.37392732  0.6368964 ]
 [ 0.34046109  0.28064583  0.71247776]]


In [3]:
eigenValues = qrAlgorithm(q,r)


values, vectors = eig(A)

print("numpy eigValues: \n", values)
print("nossos eigValues: \n",eigenValues)

numpy eigValues: 
 [ 1.66364028 -0.69140876  0.24784952]
nossos eigValues: 
 [ 1.66364028  0.69140876  0.24784952]
